[package]
name = "barehand"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.8"
sdl2 = { version = "0.35", features = [ "ttf", "image" ] }
bitflags = "2.3"